sudo: required
services:
  - docker

before_install:
  - docker build -t mouhib/react-test -f ./client/DockerFile.dev ./client

script:
  - docker run -e CI=true mouhib/react-test npm run test -- --coverage

after_success:
  - docker build -t mouhib/multi-client ./client
  - docker build -t mouhib/multi-nginx ./nginx
  - docker build -t mouhib/multi-server ./server
  - docker build -t mouhib/multi-worker ./worker
 #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # take those images and push them to docker hub
  - docker push mouhib/multi-client
  - docker push mouhib/multi-nginx
  - docker push mouhib/multi-server
  - docker push mouhib/multi-worker
  